# Jenkins icon https://jenkins.io/
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      This is a workflow template that allows you to run a Jenkinsfile pipeline in a
      container by using the `jenkins/jenkinsfile-runner` image.
    workflows.argoproj.io/maintainer: '@dcherman'
    workflows.argoproj.io/tags: jenkins,ci
    workflows.argoproj.io/version: '>= 2.9.0'
  name: jenkins-pipeline
spec:
  entrypoint: run-jenkins-pipeline
  templates:
  - name: run-jenkins-pipeline
    inputs:
      artifacts:
        - name: jenkinsfile
          path: /jenkinsfile
          git:
            repo: 'https://github.com/itumor/argoworkflowjenkins.git'
            path: 'Jenkinsfile'
        - name: plugins
          path: /plugins.txt
          git:
            repo: 'https://github.com/itumor/argoworkflowjenkins.git'
            path: 'plugins.txt'
          optional: true
      parameters:
      - name: image
        value: jenkins/jenkinsfile-runner
      - name: build-number
        value: 1
      - name: cause
        value: "argo-workflow"
      - name: job-name
        value: "job"
    script:
      image: "{{inputs.parameters.image}}"
      command: [bash]
      source: |
        set -euox pipefail

        ARGS=(--file="/jenkinsfile")
        ARGS+=(--build-number="{{inputs.parameters.build-number}}")
        ARGS+=(--cause="{{inputs.parameters.cause}}")
        ARGS+=(--job-name="{{inputs.parameters.job-name}}")

        if [[ -f /plugins.txt ]]; then
          ARGS+=(--plugins="/   .txt")
        fi

        /app/bin/jenkinsfile-runner-launcher "${ARGS[@]}"