# Jenkins icon https://jenkins.io/
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      This is a workflow template that allows you to run a Jenkinsfile pipeline in a
      container by using the `jenkins/jenkinsfile-runner:latest` image.
    workflows.argoproj.io/maintainer: '@dcherman'
    workflows.argoproj.io/tags: jenkins,ci
    workflows.argoproj.io/version: '>= 2.9.0'
  name: jenkins-pipeline
spec:
  entrypoint: run-jenkins-pipeline
  templates:
  - name: run-jenkins-pipeline
    inputs:
      artifacts:
        - name: jenkinsfile
          path: /pipeline/jenkinsfile
          git:
            repo: 'https://github.com/itumor/argoworkflowjenkins.git'
      parameters:
      - name: image
        value: jenkins/jenkinsfile-runner:latest
      - name: build-number
        value: 1
      - name: cause
        value: "argo-workflow"
      - name: job-name
        value: "job"
    script:
      image: "{{inputs.parameters.image}}"
      command: [bash]
      source: |
        set -euox pipefail

        ARGS=(--build-number="{{inputs.parameters.build-number}}")
        ARGS+=(--cause="{{inputs.parameters.cause}}")
        ARGS+=(--job-name="{{inputs.parameters.job-name}}")
        cp -r /pipeline/jenkinsfile /tmp/jenkins
        cp -r /pipeline/jenkinsfile /workspace
        cp -r /pipeline/jenkinsfile/plugins.txt /usr/share/jenkins/ref/plugins/plugins.txt
        ls -la /tmp/jenkins
        ls -la /workspace
        ls -la /usr/share/jenkins/ref/plugins
        /app/bin/jenkinsfile-runner  -p /tmp/jenkins/plugins.txt  -f /workspace -jv 2.346.1  "${ARGS[@]}"
